### ISSUE TITLE
Build Static Site

### ISSUE THREAD

**Issue by Gorcenski** [Gorcenski/women-streets-berlin#8]
## Vision

The public-facing part of this project will be a static site capable of displaying content about the streets of Berlin, showing some qualitative and quantitative analysis, and providing means for users to contribute content of their own.

The static site model is chosen because hosting is inexpensive and portable. Any user can replicate the site simply by downloading the content, and no additional tooling or configuration is required to host the site anywhere. This is particularly well-suited for archival tools, wherein dependencies on software severely hinder the longevity of the archive.

A suitable Static Site Generator will need to be selected. Some of the requirements:

- Easy to install with several templates
- Ability to configure and generate plaintext content
- Ability to differentiate content types, e.g. posts vs. pages
- Easy integration of third party JS tools

For the purposes of this milestone, configuring hosting will be considered separate. The desired MVP is a working, semi-styled static site capable of displaying content and providing tools for contributors. It is acceptable to have a working site running in dev.

## Approach

For the approach, the following steps will be taken:

- [ ] Select a SSG (#9)
- [ ] Select a suitable template (#10)
- [ ] Configure basic landing page and taxonomies (#11)
- [ ] Build templates for index content
- [ ] Build templates for granular content

With respect to the last two points, those may become epics or milestones themselves.
